ALTER TABLE agents ADD COLUMN IF NOT EXISTS container_id TEXT;
ALTER TABLE agents ADD COLUMN IF NOT EXISTS provision_log TEXT NOT NULL DEFAULT '';
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS tmux_window TEXT;
